;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	autopair-insert-or-skip-quote
	cua--prefix-override-handler
	dabbrev-expand
	indent-for-tab-command
	))

(setq mc/cmds-to-run-once
      '(
	*table--cell-delete-backward-char
	autopair-newline
	autopair-skip-close-maybe
	cua-paste
	))
